### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by AntonJoha** [SegHaxx/curdle#1]
Played your game and wanted to quit, tried doing this with ^D. See attached image for result. 

![2022-05-18 13:19:52](https://user-images.githubusercontent.com/75372329/169027832-f3cf2f96-c98e-4b53-8721-366c5fc9fe86.png)

**Comment by AntonJoha** [comment]
For more context, this was done on the ssh server I found through your twitter account

**Comment by SegHaxx** [comment]
yup, weird last minute bug!

it is in fact, cursed 🙃

**Comment by SegHaxx** [comment]
okay easy fix, need to check for fgets returning error and exit() instead of going into an infinite loop 4b00694a3f3c709bf30aa13f6a67b6323fee2858

**Comment by SegHaxx** [comment]
okay easy fix, need to check for fgets returning error and exit() instead of going into an infinite loop 4b00694a3f3c709bf30aa13f6a67b6323fee2858
